sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - clang-format-3.8
      - g++-5

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - $CXX -v && $CC -v

  # Install dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install recent Boost (1.60.0)
  - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz"
  - mkdir boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost
  - cd boost && mkdir build
  - ./bootstrap.sh --with-libraries=log,thread,filesystem,date_time,system --prefix=${DEPS_DIR}/boost/build
  - ./b2 -j4 -d0 --with-log --with-thread --with-filesystem --with-date_time --with-system threading=multi link=static install
  - if [[ -d ${DEPS_DIR}/boost ]]; then CMAKE_OPTIONS+=" -DBOOST_ROOT=${DEPS_DIR}/boost/build"; fi

  # Install recent CMake (3.4.2)
  - CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.2.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - cd cmake && ./bootstrap --parallel=4 && make -j4 -s
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH} && cmake --version

script:
  - cd "${TRAVIS_BUILD_DIR}" && mkdir build && cd build
  - cmake .. ${CMAKE_OPTIONS}
  - make VERBOSE=1
