sudo: false

language: cpp


addons:
  apt:
    sources: &global_sources [ 'boost-latest', 'kalakris-cmake' ]
    packages: &global_packages [ 'libboost1.55-all-dev', 'cmake' ]


matrix:
  # TODO: GCC has weird link errors with Boost libraries.
  # I don't see it on my system (Ubu 15.04). May be recompile Boost on Travis?
  allow_failures:
    - compiler: gcc

  include:
    ### LINUX builds ----
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: [*global_sources, 'ubuntu-toolchain-r-test']
          packages: [*global_packages, 'gcc-4.9', 'g++-4.9']
      env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BUILD_TYPE=Release

    - os: linux
      compiler: gcc
      addons: *gcc49
      env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BUILD_TYPE=Debug


    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: [*global_sources, 'ubuntu-toolchain-r-test']
          packages: [*global_packages, 'gcc-5', 'g++-5']
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE=Release

    - os: linux
      compiler: gcc
      addons: *gcc5
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE=Debug


    - os: linux
      compiler: clang
      addons: &clang37
        apt:
          sources: [*global_sources, 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: [*global_packages, 'clang-3.7', 'gcc-4.9', 'g++-4.9']
      env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BUILD_TYPE=Release

    - os: linux
      compiler: clang
      addons: *clang37
      env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BUILD_TYPE=Debug


    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: [*global_sources, 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: [*global_packages, 'clang-3.8', 'gcc-4.9', 'g++-4.9']
      env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE=Release

    - os: linux
      compiler: clang
      addons: *clang38
      env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE=Debug

    ### TODO: Max OS X builds ----

before_script:
  - export CXX=$CXX_COMPILER CC=$C_COMPILER
  - $CXX -v && $CC -v

script:
  - cd "${TRAVIS_BUILD_DIR}" && mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make VERBOSE=1
