language: cpp

compiler:
#  - clang
  - gcc

addons:
  apt:
    sources:
      - boost-latest
#      - llvm-toolchain-precise-3.6
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
#      - clang-3.6
#      - clang-format-3.6
      - cmake
      - g++-5
      - libboost1.55-all-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
#  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
